### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by U1320100568** [U1320100568/Mvc-third#6]
內容或按鈕等高
```CSS
.btn-container {
    display: inline-flex;
}
.btn-item {
    flex-grow:1;
}
```
